### ISSUE TITLE
/etc/secret-volume/env-var

### ISSUE THREAD

**Issue by nanek** [TryStarboard/Starboard#41]
What is `/etc/secret-volume/env-var` for?

```
{ [Error: ENOENT: no such file or directory, open '/etc/secret-volume/env-var']
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/etc/secret-volume/env-var' }
```

I can create this, and the error goes away.

**Comment by d6u** [comment]
Ideally if you have `NODE_ENV=development` this error should be silenced. But this is referring to production secrets. The file is defined in [Kubernetes pod sepc](https://github.com/TryStarboard/Starboard/blob/0512ef8d9a898012b7dda91045f09af628d8e14f/starboard-replication-controller.yml.tmpl#L34-L37). Relevant code that emit this error is [here](https://github.com/TryStarboard/Starboard/blob/0512ef8d9a898012b7dda91045f09af628d8e14f/source/server/bootstrap/loadEnv.js).

**Comment by nanek** [comment]
Ok, that makes sense. I'm trying to debug why `npm run dev` does not start the server properly. If I run `node build/server.js` in another window it works fine.

**Comment by d6u** [comment]
Yeah, I recently figured `npm run dev` is doing too many things. Sometimes the sequences will mess up. Recently I normally run those in separate window and one after another (run next when previous one generates some content):
1. `npm run watch:build`
2. `npm run run-non-server`
3. `npm run run-server`

It's annoying that you have to run three commands in different windows and command 2 will open browser without any content, but it works after commands 3 runs successfully.

---

Alternatively you can run:
1. `docker-compose up`
2. `node --harmony_default_parameters --harmony_destructuring script/dev.js`

But nodemon has bugs when being required and starts multiple child processes, which will cause job server stops responding to enqueued jobs. But the http server runs just fine. If you know what's going on with `script/dev.js`, PRs are welcome :smile:

**Comment by d6u** [comment]
BTW, I'm using Node 5.9.0

**Comment by nanek** [comment]
Ok, thanks!
